version: 0.2

phases:
  pre_build:
    commands:
      -  aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin  830347306116.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build -t hellowworldaws:latest .
      - docker tag  hellowworldaws:latest 830347306116.dkr.ecr.us-east-1.amazonaws.com/demo-ear:latest
  post_build:
    commands:
      - docker push 830347306116.dkr.ecr.us-east-1.amazonaws.com/demo-ear
      - printf '[{"name":HelloLokeshTask,"830347306116.dkr.ecr.us-east-1.amazonaws.com/demo-ear":"%s"}]' 830347306116.dkr.ecr.us-east-1.amazonaws.com > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
